language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t a14c0ffe-c15f-4fc9-a314-9c50a3b8627b

before_install:
  - chmod +x mvnw

